// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
  
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("RomSort")]
[assembly: AssemblyDescription("Sort roms into alphabetical folders.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Jon Thysell")]
[assembly: AssemblyProduct("RomSort")]
[assembly: AssemblyCopyright("Copyright © Jon Thysell 2018-2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: NeutralResourcesLanguage("en")]